trade-gui:
  fill_panel:
    - 2
    - 4
    - 6
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 22
    - 31
    - 40
    - 49
  accept_btn-1: 0
  accept_btn-2: 8
  profile_slot-1: 3
  profile_slot-2: 5
  interact_slot-1:
    - 18
    - 19
    - 20
    - 21
    - 27
    - 28
    - 29
    - 30
    - 36
    - 37
    - 38
    - 39
    - 45
    - 46
    - 47
    - 48
  interact_slot-2:
    - 23
    - 24
    - 25
    - 26
    - 32
    - 33
    - 34
    - 35
    - 41
    - 42
    - 43
    - 44
    - 50
    - 51
    - 52
    - 53